import { Geist, Geist_Mono } from "next/font/google";
import Navbar from "@/components/home/Navbar";
import Footer from "@/components/home/Footer";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className="bg-green-50 text-gray-800">
        <Navbar />
        <main className="min-h-screen px-6 py-12">{children}</main>
        <Footer />
      </body>
    </html>
  );
}
